name: Automated Unit Testing
on:
  push:
    branches:
      - main
jobs:
  web-tests:
    name: Automate Tests
    runs-on: ubuntu-latest
    steps:
    - name: Testing
      run: vendor\bin\phpunit
